{
 "title": "fuji test2",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "ETHUSDC-DEBT ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "data": "{\"only\":[\"ETHUSDC-DEBT\"]}",
     "target": "ETHUSDC-DEBT",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "ETHDAI-DEBT ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "data": "{\"only\":[\"ETHDAI-DEBT\"]}",
     "target": "ETHDAI-COLL",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "ETHUSDC-COLL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "data": "{\"only\":[\"ETHUSDC-COLL\"]}",
     "target": "ETHUSDC-DEBT",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "ETHDAI-COLL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "data": "{\"only\":[\"ETHDAI-COLL\"]}",
     "target": "ETHUSDC-DEBT",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Active Addresses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "data": "{\"only\":[\"USERSWITHDEBT\"]}",
     "target": "ETHUSDC-DEBT",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Rates USDC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "data": "{\"only\":[ \"DYDXUSDC\",\"AAVEUSDC\",\"COMPOUNDUSDC\"]}",
     "target": "COMPOUNDUSDC",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Rates DAI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "data": "{\"only\":[ \"DYDXDAI\",\"AAVEDAI\",\"COMPOUNDDAI\"]}",
     "target": "COMPOUNDUSDC",
     "type": "timeseries"
    }
   ]
  }
 ]
}